version: 0.2

env:
  variables:
    NODE_ENV: production
  parameter-store:
    NEXT_PUBLIC_GA_MEASUREMENT_ID: /CodeBuild/hbdesign/${ENV}/ga_measurement_id
    AWS_S3_BUCKET: /CodeBuild/hbdesign/${ENV}/s3_bucket
    CLOUDFRONT_DISTRIBUTION_ID: /CodeBuild/hbdesign/${ENV}/cloudfront_id
    GITHUB_TOKEN: /hbdesign/github_token
    GALLERY_BUCKET_NAME: /CodeBuild/hbdesign/${ENV}/gallery_bucket
    APPSYNC_API_KEY: /CodeBuild/hbdesign/${ENV}/appsync_api_key
    APPSYNC_URL: /CodeBuild/hbdesign/${ENV}/appsync_url
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

  pre_build:
    commands:
      # Create environment file
      - echo "Starting pre_build phase..."
      - echo "Creating .env.production file..."
      - |
        cat << EOF > .env.production
        NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        EOF
        export GALLERY_BUCKET_NAME=${GALLERY_BUCKET_NAME}
      - npm run sync-gallery -- featured featured
#      # Sync gallery images
      - npm run sync-gallery -- Events-Decor gallery
      - npm run sync-gallery -- Illustration gallery
      - npm run sync-gallery -- Paper-Sculpture gallery
      - npm run sync-gallery -- Hero basic
#      # Sync product images
      - npm run sync-gallery -- Flower-Rentals product
      - npm run sync-gallery -- Flower-Videos basic

  build:
    commands:
      - echo "Building the application..."
      - npm run build

  post_build:
    commands:
      # Upload to S3
      - aws s3 sync out/ s3://${AWS_S3_BUCKET}/ --delete
      # Invalidate CloudFront cache
      # Invalidate CloudFront cache only if ENV is not DEV
      - |
        if [ "$(echo "${ENV}" | tr '[:lower:]' '[:upper:]')" == "PRD" ]; then
          echo "Performing CloudFront invalidation..."
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*" || {
            echo "CloudFront invalidation failed";
            exit 1;
          }
        else
          echo "Skipping CloudFront invalidation in DEV environment"
        fi 

artifacts:
  base-directory: out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
