version: 0.2

env:
  variables:
    NODE_ENV: production
  parameter-store:
    NEXT_PUBLIC_GA_MEASUREMENT_ID: /CodeBuild/hbdesign/${ENV}/ga_measurement_id
    AWS_S3_BUCKET: /CodeBuild/hbdesign/${ENV}/s3_bucket
    CLOUDFRONT_DISTRIBUTION_ID: /CodeBuild/hbdesign/${ENV}/cloudfront_id
    GITHUB_TOKEN: /hbdesign/github_token
    GALLERY_BUCKET_NAME: /CodeBuild/hbdesign/${ENV}/gallery_bucket
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
#      - npm install -g jest

#  pre_build:
#    commands:
#      - echo "Running tests..."
#      - npm run test
#      - npm run test:e2e
#      - npm run validate-links

  pre_build:
    commands:
      # Create environment file
      - echo "Creating .env.production file..."
      - |
        cat << EOF > .env.production
        NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        EOF
        export GALLERY_BUCKET_NAME=${GALLERY_BUCKET_NAME}
      - npm run sync-gallery -- hero
      - npm run sync-gallery -- featured
      - npm run sync-gallery -- paper-events
      - npm run sync-gallery -- illustration
      - npm run sync-gallery -- design
      - npm run sync-gallery -- paper-advertising

  build:
    commands:
      - echo "Building the application..."
      - npm run build

  post_build:
    commands:
      # Upload to S3
      - aws s3 sync out/ s3://${AWS_S3_BUCKET}/ --delete
      # Invalidate CloudFront cache
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  base-directory: out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
