version: 0.2

env:
  variables:
    NODE_ENV: production
  parameter-store:
    NEXT_PUBLIC_GA_MEASUREMENT_ID: /CodeBuild/hbdesign/${ENV}/ga_measurement_id
    AWS_S3_BUCKET: /CodeBuild/hbdesign/${ENV}/s3_bucket
    CLOUDFRONT_DISTRIBUTION_ID: /CodeBuild/hbdesign/${ENV}/cloudfront_id
    GITHUB_TOKEN: /hbdesign/github_token

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npm install -g jest

  pre_build:
    commands:
      - echo "Running tests..."
      - npm run test
#      - npm run test:e2e
#      - npm run validate-links

  build:
    commands:
      - echo "Building the application..."
      - npm run build

  post_build:
    commands:
      # Upload to S3
      - aws s3 sync out/ s3://${AWS_S3_BUCKET}/ --delete
      # Invalidate CloudFront cache
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  base-directory: out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
